services:
  dashboard:
    image: floodnut/initcloud_board
    container_name: initcloud_board
    env_file:
     - .env
    ports:
      - ${BOARD_PORT}:80
    depends_on:
      - springboot
    restart: always
  db:
    image: floodnut/initcloud_db
    container_name: initcloud_db
    volumes:
      - ./db/data:/var/lib/mariadb:rw
    env_file:
     - .env
    environment:
        TZ: Asia/Seoul
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - ${DB_PORT}:3306
    restart: always
  fastapi:
    container_name: initcloud_parser
    image: floodnut/parser_api 
    volumes:
      - ./backend_scanner/uploads:/app/uploads
    ports:
      - ${PARSER_PORT}:8000
    env_file:
     - .env
  springboot:
    container_name: initcloud_scanner
    image: floodnut/initcloud_api 
    volumes:
      - ./backend_scanner/uploads:/app/uploads
    ports:
      - ${SCANNER_PORT}:8080
    env_file:
     - .env
    restart: always
    depends_on:     
     - db
     - fastapi
