spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 15MB
      max-request-size: 45MB
      location: uploads/
  rabbitmq:
    host: localhost
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PW}
