name: SCANNER-Snapshot CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_SERVER_HOST }}
          username: ${{ secrets.API_SERVER_SSH_ID }}
          key: ${{ secrets.API_SERVER_SSH }}
          port: ${{ secrets.API_SERVER_PORT }}
          script: |
            DATE=$(date "+%y.%m.%d")
            docker build -t ${{ secrets.REGISTRY_001 }}/scanner_api:v2-$DATE ./backend-scanner/
            docker build -t ${{ secrets.REGISTRY_001 }}/scanner_api:v2 ./backend-scanner/
            docker push ${{ secrets.REGISTRY_001 }}/scanner_api:v2-$DATE
            docker push ${{ secrets.REGISTRY_001 }}/scanner_api:v2
            docker compose up -d 
